import { z } from "zod";
import { SeveritySchema } from "./severity.js";

const GradeSchema = z.enum(["S", "A+", "A", "B+", "B", "C+", "C", "D", "F"]);

export const InstanceContextSchema = z.object({
  parentInstanceNodeId: z.string(),
  sourceNodeId: z.string(),
  sourceComponentId: z.string().optional(),
  sourceComponentName: z.string().optional(),
});

export type InstanceContext = z.infer<typeof InstanceContextSchema>;

/**
 * Apply-strategy enum surfaced on survey questions and analyze-output issues.
 * Mirrors `RuleApplyStrategy` in `src/core/gotcha/apply-context.ts` —
 * declared as a Zod enum here so MCP responses validate end-to-end.
 */
export const RuleApplyStrategySchema = z.enum([
  "property-mod",
  "structural-mod",
  "annotation",
  "auto-fix",
]);

export type RuleApplyStrategy = z.infer<typeof RuleApplyStrategySchema>;

const TargetPropertySchema = z.union([z.string(), z.array(z.string())]);

/**
 * Mirrors the `AnnotationProperty` interface in `src/core/roundtrip/types.ts`.
 * Declared here per the project's Zod convention (schemas live in contracts/)
 * so MCP responses validate end-to-end.
 */
export const AnnotationPropertySchema = z.object({ type: z.string() });

export const GotchaSurveyQuestionSchema = z.object({
  nodeId: z.string(),
  nodeName: z.string(),
  ruleId: z.string(),
  severity: SeveritySchema,
  question: z.string(),
  hint: z.string(),
  example: z.string(),
  instanceContext: InstanceContextSchema.optional(),
  applyStrategy: RuleApplyStrategySchema,
  targetProperty: TargetPropertySchema.optional(),
  annotationProperties: z.array(AnnotationPropertySchema).optional(),
  suggestedName: z.string().optional(),
  isInstanceChild: z.boolean(),
  sourceChildId: z.string().optional(),
  // #356: when this question collapses N instance-child issues that share the
  // same `(sourceComponentId, sourceNodeId, ruleId)` tuple, `replicas` is the
  // total instance count (>=2) and `replicaNodeIds` lists every instance scene
  // node id OTHER than the kept `nodeId`. Apply step iterates
  // `[nodeId, ...replicaNodeIds]` so the same answer lands on every replica.
  // Single-instance questions omit both fields.
  replicas: z.number().int().min(2).optional(),
  replicaNodeIds: z.array(z.string()).optional(),
});

export type GotchaSurveyQuestion = z.infer<typeof GotchaSurveyQuestionSchema>;

/**
 * Pre-grouped+batched view of `questions` (#369, #370, #381). Decoupled from
 * `questions` so consumers that just want the flat list can ignore it; SKILLs
 * (`canicode-gotchas`, `canicode-roundtrip`) iterate over `groupedQuestions`
 * to keep sort / partition / batchable-rule decisions out of the LLM's
 * prose interpretation, per ADR-016.
 *
 * Generated by `groupAndBatchSurveyQuestions` in `core/gotcha/`. Sort key is
 * `(sourceComponentId ?? "_no-source", ruleId, nodeName)`. Source-component
 * groups are emitted first; the trailing group with `instanceContext: null`
 * carries every non-instance question.
 */
export const SurveyQuestionBatchSchema = z.object({
  ruleId: z.string(),
  /**
   * `true` when every member shares an answer-shape uniformly applicable to
   * all of them (e.g. one `min-width` value covers all FILL children).
   * The SKILL renders one shared prompt for `batchable: true` batches with
   * `questions.length >= 2`; everything else falls through to the
   * single-question template.
   */
  batchable: z.boolean(),
  questions: z.array(GotchaSurveyQuestionSchema),
  /**
   * Sum of `max(question.replicas, 1)` across `questions`. Counts the
   * actual Figma scene fan-out so the SKILL can render `N instances`
   * accurately even when one batch member already collapses multiple
   * replicas via the #356 source-component dedupe.
   */
  totalScenes: z.number().int().min(1),
});

export type SurveyQuestionBatch = z.infer<typeof SurveyQuestionBatchSchema>;

export const SurveyQuestionGroupSchema = z.object({
  /**
   * Shared `instanceContext` for the group, or `null` for the trailing
   * non-instance group. The SKILL emits the verbose "Instance note" header
   * once per non-null group instead of once per question (#370).
   */
  instanceContext: InstanceContextSchema.nullable(),
  batches: z.array(SurveyQuestionBatchSchema),
});

export type SurveyQuestionGroup = z.infer<typeof SurveyQuestionGroupSchema>;

export const GroupedSurveySchema = z.object({
  groups: z.array(SurveyQuestionGroupSchema),
});

export type GroupedSurvey = z.infer<typeof GroupedSurveySchema>;

export const GotchaSurveySchema = z.object({
  designGrade: GradeSchema,
  isReadyForCodeGen: z.boolean(),
  questions: z.array(GotchaSurveyQuestionSchema),
  groupedQuestions: GroupedSurveySchema,
  /**
   * #384 — canonical identifier for this design across canicode runs.
   * Computed by `computeDesignKey(input)` (`<fileKey>#<nodeId>` for Figma
   * URLs, absolute path for fixtures). The `canicode-gotchas` SKILL reads
   * this directly when upserting the per-design section, so the SKILL.md
   * prose no longer parses URLs (per ADR-016).
   */
  designKey: z.string(),
});

export type GotchaSurvey = z.infer<typeof GotchaSurveySchema>;
