import type { AnalysisNode } from "../contracts/figma-node.js";

/**
 * Style properties extracted from Tailwind/JSX code generated by Figma MCP get_design_context.
 * These are merged into AnalysisNode to enrich metadata-only nodes with style information.
 */
export interface ExtractedStyles {
  layoutMode?: "HORIZONTAL" | "VERTICAL";
  layoutPositioning?: "AUTO" | "ABSOLUTE";
  layoutSizingHorizontal?: "FIXED" | "HUG" | "FILL";
  layoutSizingVertical?: "FIXED" | "HUG" | "FILL";
  itemSpacing?: number;
  paddingLeft?: number;
  paddingRight?: number;
  paddingTop?: number;
  paddingBottom?: number;
  fills?: unknown[];
  effects?: unknown[];

  // Responsive fields
  minWidth?: number;
  maxWidth?: number;
  minHeight?: number;
  maxHeight?: number;
  layoutWrap?: "WRAP" | "NO_WRAP";
  counterAxisSpacing?: number;
  clipsContent?: boolean;
  overflowDirection?: "HORIZONTAL_SCROLLING" | "VERTICAL_SCROLLING" | "HORIZONTAL_AND_VERTICAL_SCROLLING";
}

/**
 * A code block from get_design_context, associated with a node ID.
 */
export interface DesignContextBlock {
  nodeId: string;
  code: string;
}

// Tailwind spacing scale: class suffix → px value
const SPACING_SCALE: Record<string, number> = {
  "0": 0, "px": 1, "0.5": 2, "1": 4, "1.5": 6, "2": 8, "2.5": 10,
  "3": 12, "3.5": 14, "4": 16, "5": 20, "6": 24, "7": 28, "8": 32,
  "9": 36, "10": 40, "11": 44, "12": 48, "14": 56, "16": 64,
  "20": 80, "24": 96, "28": 112, "32": 128, "36": 144, "40": 160,
  "44": 176, "48": 192, "52": 208, "56": 224, "60": 240, "64": 256,
  "72": 288, "80": 320, "96": 384,
};

function resolveSpacing(value: string): number | undefined {
  // Arbitrary value: gap-[12px]
  const arbMatch = value.match(/^\[(\d+(?:\.\d+)?)px\]$/);
  if (arbMatch?.[1]) return parseFloat(arbMatch[1]);
  return SPACING_SCALE[value];
}

/**
 * Extract style properties from a className string (Tailwind classes).
 */
export function extractStylesFromClasses(classes: string): ExtractedStyles {
  const styles: ExtractedStyles = {};
  const tokens = classes.split(/\s+/);
  let gapX: number | undefined;
  let gapY: number | undefined;
  let gap: number | undefined;
  let overflowX = false;
  let overflowY = false;
  let overflowXHidden = false;
  let overflowYHidden = false;

  for (const token of tokens) {
    // Layout direction
    if (token === "flex" || token === "flex-row") {
      styles.layoutMode = "HORIZONTAL";
    } else if (token === "flex-col") {
      styles.layoutMode = "VERTICAL";
    }

    // Positioning
    else if (token === "absolute") {
      styles.layoutPositioning = "ABSOLUTE";
    } else if (token === "relative" || token === "static") {
      styles.layoutPositioning = "AUTO";
    }

    // Sizing
    else if (token === "w-full") {
      styles.layoutSizingHorizontal = "FILL";
    } else if (token === "h-full") {
      styles.layoutSizingVertical = "FILL";
    } else if (token === "w-fit") {
      styles.layoutSizingHorizontal = "HUG";
    } else if (token === "h-fit") {
      styles.layoutSizingVertical = "HUG";
    } else if (token.match(/^w-\[.+\]$/) || token.match(/^w-\d/)) {
      styles.layoutSizingHorizontal = "FIXED";
    } else if (token.match(/^h-\[.+\]$/) || token.match(/^h-\d/)) {
      styles.layoutSizingVertical = "FIXED";
    }

    // Gap → deferred until layoutMode is known (gap-x-*/gap-y-* must be checked before gap-*)
    else if (token.startsWith("gap-y-")) {
      gapY = resolveSpacing(token.slice(6));
    } else if (token.startsWith("gap-x-")) {
      gapX = resolveSpacing(token.slice(6));
    } else if (token.startsWith("gap-")) {
      const val = token.slice(4);
      const px = resolveSpacing(val);
      if (px !== undefined) gap = px;
    }

    // Padding
    else if (token.startsWith("p-") && !token.startsWith("pl-") && !token.startsWith("pr-") && !token.startsWith("pt-") && !token.startsWith("pb-") && !token.startsWith("px-") && !token.startsWith("py-")) {
      const val = token.slice(2);
      const px = resolveSpacing(val);
      if (px !== undefined) {
        styles.paddingLeft = px;
        styles.paddingRight = px;
        styles.paddingTop = px;
        styles.paddingBottom = px;
      }
    } else if (token.startsWith("px-")) {
      const px = resolveSpacing(token.slice(3));
      if (px !== undefined) {
        styles.paddingLeft = px;
        styles.paddingRight = px;
      }
    } else if (token.startsWith("py-")) {
      const px = resolveSpacing(token.slice(3));
      if (px !== undefined) {
        styles.paddingTop = px;
        styles.paddingBottom = px;
      }
    } else if (token.startsWith("pl-")) {
      const px = resolveSpacing(token.slice(3));
      if (px !== undefined) styles.paddingLeft = px;
    } else if (token.startsWith("pr-")) {
      const px = resolveSpacing(token.slice(3));
      if (px !== undefined) styles.paddingRight = px;
    } else if (token.startsWith("pt-")) {
      const px = resolveSpacing(token.slice(3));
      if (px !== undefined) styles.paddingTop = px;
    } else if (token.startsWith("pb-")) {
      const px = resolveSpacing(token.slice(3));
      if (px !== undefined) styles.paddingBottom = px;
    }

    // Min/max width
    else if (token.startsWith("min-w-")) {
      const px = resolveSpacing(token.slice(6));
      if (px !== undefined) styles.minWidth = px;
    } else if (token.startsWith("max-w-")) {
      const px = resolveSpacing(token.slice(6));
      if (px !== undefined) styles.maxWidth = px;
    }

    // Min/max height
    else if (token.startsWith("min-h-")) {
      const px = resolveSpacing(token.slice(6));
      if (px !== undefined) styles.minHeight = px;
    } else if (token.startsWith("max-h-")) {
      const px = resolveSpacing(token.slice(6));
      if (px !== undefined) styles.maxHeight = px;
    }

    // Flex wrap
    else if (token === "flex-wrap") {
      styles.layoutWrap = "WRAP";
    } else if (token === "flex-nowrap") {
      styles.layoutWrap = "NO_WRAP";
    }

    // Overflow
    else if (token === "overflow-hidden") {
      styles.clipsContent = true;
    } else if (token === "overflow-x-hidden") {
      overflowXHidden = true;
    } else if (token === "overflow-y-hidden") {
      overflowYHidden = true;
    } else if (token === "overflow-x-auto" || token === "overflow-x-scroll") {
      overflowX = true;
    } else if (token === "overflow-y-auto" || token === "overflow-y-scroll") {
      overflowY = true;
    } else if (token === "overflow-auto" || token === "overflow-scroll") {
      overflowX = true;
      overflowY = true;
    }

    // Background color → fills
    else if (token.startsWith("bg-[")) {
      const colorMatch = token.match(/^bg-\[(.+)\]$/);
      if (colorMatch?.[1]) {
        const color = colorMatch[1];
        if (!styles.fills) styles.fills = [];
        if (color.startsWith("var(")) {
          // Design token reference: bg-[var(--md-sys-color-surface)]
          styles.fills.push({ type: "SOLID", color: {}, boundVariable: color });
        } else {
          // Raw color: bg-[#FF0000]
          styles.fills.push({ type: "SOLID", color: parseHexColor(color) });
        }
      }
    }

    // Shadow → effects
    else if (token === "shadow" || token.startsWith("shadow-")) {
      if (!styles.effects) styles.effects = [];
      styles.effects.push({ type: "DROP_SHADOW" });
    }
  }

  // Resolve gap based on final layout direction
  // Generic gap-* applies to both axes, directional gap-x-*/gap-y-* override specific axes
  // In flex-row (HORIZONTAL): gap-x → itemSpacing (main), gap-y → counterAxisSpacing (cross)
  // In flex-col (VERTICAL): gap-y → itemSpacing (main), gap-x → counterAxisSpacing (cross)
  const isColumn = styles.layoutMode === "VERTICAL";
  if (gap !== undefined) {
    if (gapX === undefined) {
      if (isColumn) styles.counterAxisSpacing = gap;
      else styles.itemSpacing = gap;
    }
    if (gapY === undefined) {
      if (isColumn) styles.itemSpacing = gap;
      else styles.counterAxisSpacing = gap;
    }
  }
  if (gapX !== undefined) {
    if (isColumn) styles.counterAxisSpacing = gapX;
    else styles.itemSpacing = gapX;
  }
  if (gapY !== undefined) {
    if (isColumn) styles.itemSpacing = gapY;
    else styles.counterAxisSpacing = gapY;
  }

  // Resolve overflow direction from collected flags
  // Hidden flags suppress scrolling on that axis
  const effectiveX = overflowX && !overflowXHidden;
  const effectiveY = overflowY && !overflowYHidden;
  if (effectiveX && effectiveY) {
    styles.overflowDirection = "HORIZONTAL_AND_VERTICAL_SCROLLING";
  } else if (effectiveX) {
    styles.overflowDirection = "HORIZONTAL_SCROLLING";
  } else if (effectiveY) {
    styles.overflowDirection = "VERTICAL_SCROLLING";
  }
  // Axis-specific hidden implies clipping on that axis
  if (overflowXHidden || overflowYHidden) {
    styles.clipsContent = true;
  }

  return styles;
}

function parseHexColor(hex: string): Record<string, number> {
  const clean = hex.replace("#", "");
  if (clean.length === 6 || clean.length === 8) {
    return {
      r: parseInt(clean.slice(0, 2), 16) / 255,
      g: parseInt(clean.slice(2, 4), 16) / 255,
      b: parseInt(clean.slice(4, 6), 16) / 255,
      a: clean.length === 8 ? parseInt(clean.slice(6, 8), 16) / 255 : 1,
    };
  }
  return { r: 0, g: 0, b: 0, a: 1 };
}

/**
 * Extract className values from the root-level JSX element in a code block.
 * Returns classes from the first/outermost div/element's className.
 */
function extractRootClasses(code: string): string {
  // Match the first className="..." in the JSX
  const match = code.match(/className="([^"]+)"/);
  return match?.[1] ?? "";
}

/**
 * Extract all className values from entire code block.
 * Returns aggregated style info for all elements.
 */
function extractAllClasses(code: string): string[] {
  const classes: string[] = [];
  const regex = /className="([^"]+)"/g;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(code)) !== null) {
    if (match[1]) classes.push(match[1]);
  }
  return classes;
}

/**
 * Parse a get_design_context code response to extract style hints
 * for enriching AnalysisNode properties.
 *
 * The code is React+Tailwind generated by Figma MCP. We extract:
 * - Root element styles (layoutMode, padding, gap, sizing)
 * - Color fills (bg-[#hex] or bg-[var(...)])
 * - Shadow effects
 * - Layout positioning (absolute/relative)
 */
export function parseDesignContextCode(code: string): ExtractedStyles {
  const rootClasses = extractRootClasses(code);
  const rootStyles = extractStylesFromClasses(rootClasses);

  // Also scan all elements for fills and effects to capture deeper style info
  const allClasses = extractAllClasses(code);
  const aggregatedFills: unknown[] = [...(rootStyles.fills ?? [])];
  const aggregatedEffects: unknown[] = [...(rootStyles.effects ?? [])];

  for (const cls of allClasses) {
    const styles = extractStylesFromClasses(cls);
    if (styles.fills) {
      for (const fill of styles.fills) aggregatedFills.push(fill);
    }
    if (styles.effects) {
      for (const effect of styles.effects) aggregatedEffects.push(effect);
    }
  }

  return {
    ...rootStyles,
    ...(aggregatedFills.length > 0 ? { fills: aggregatedFills } : {}),
    ...(aggregatedEffects.length > 0 ? { effects: aggregatedEffects } : {}),
  };
}

/**
 * Parse the comment header from get_design_context code to extract node metadata.
 * Format: "/* NodeName — 905x680 COMPONENT, vertical auto-layout *\/"
 */
export function parseCodeHeader(code: string): {
  name?: string;
  width?: number;
  height?: number;
  type?: string;
  hasAutoLayout?: boolean;
  layoutDirection?: "HORIZONTAL" | "VERTICAL";
} {
  const headerMatch = code.match(/\/\*\s*(.+?)\s*\*\//);
  if (!headerMatch?.[1]) return {};

  const header = headerMatch[1];
  const result: ReturnType<typeof parseCodeHeader> = {};

  // Extract name (before " — ")
  const nameParts = header.split(" — ");
  if (nameParts[0]) result.name = nameParts[0].trim();

  // Extract dimensions
  const dimMatch = header.match(/(\d+)x(\d+)/);
  if (dimMatch?.[1] && dimMatch[2]) {
    result.width = parseInt(dimMatch[1]);
    result.height = parseInt(dimMatch[2]);
  }

  // Extract type
  const typeMatch = header.match(/\b(COMPONENT|FRAME|INSTANCE|GROUP|SECTION)\b/);
  if (typeMatch?.[1]) result.type = typeMatch[1];

  // Auto-layout detection
  if (header.includes("no auto-layout")) {
    result.hasAutoLayout = false;
  } else if (header.includes("auto-layout")) {
    result.hasAutoLayout = true;
    if (header.includes("vertical auto-layout")) result.layoutDirection = "VERTICAL";
    else if (header.includes("horizontal auto-layout")) result.layoutDirection = "HORIZONTAL";
  }

  return result;
}

/**
 * Merge extracted styles into an AnalysisNode (mutates the node).
 * Only sets properties that are not already present on the node.
 */
export function enrichNodeWithStyles(node: AnalysisNode, styles: ExtractedStyles): void {
  if (styles.layoutMode && !node.layoutMode) node.layoutMode = styles.layoutMode;
  if (styles.layoutPositioning && !node.layoutPositioning) node.layoutPositioning = styles.layoutPositioning;
  if (styles.layoutSizingHorizontal && !node.layoutSizingHorizontal) node.layoutSizingHorizontal = styles.layoutSizingHorizontal;
  if (styles.layoutSizingVertical && !node.layoutSizingVertical) node.layoutSizingVertical = styles.layoutSizingVertical;
  if (styles.itemSpacing !== undefined && node.itemSpacing === undefined) node.itemSpacing = styles.itemSpacing;
  if (styles.paddingLeft !== undefined && node.paddingLeft === undefined) node.paddingLeft = styles.paddingLeft;
  if (styles.paddingRight !== undefined && node.paddingRight === undefined) node.paddingRight = styles.paddingRight;
  if (styles.paddingTop !== undefined && node.paddingTop === undefined) node.paddingTop = styles.paddingTop;
  if (styles.paddingBottom !== undefined && node.paddingBottom === undefined) node.paddingBottom = styles.paddingBottom;
  if (styles.fills && !node.fills) node.fills = styles.fills;
  if (styles.effects && !node.effects) node.effects = styles.effects;

  // Responsive fields
  if (styles.minWidth !== undefined && node.minWidth === undefined) node.minWidth = styles.minWidth;
  if (styles.maxWidth !== undefined && node.maxWidth === undefined) node.maxWidth = styles.maxWidth;
  if (styles.minHeight !== undefined && node.minHeight === undefined) node.minHeight = styles.minHeight;
  if (styles.maxHeight !== undefined && node.maxHeight === undefined) node.maxHeight = styles.maxHeight;
  if (styles.layoutWrap && !node.layoutWrap) node.layoutWrap = styles.layoutWrap;
  if (styles.counterAxisSpacing !== undefined && node.counterAxisSpacing === undefined) node.counterAxisSpacing = styles.counterAxisSpacing;
  if (styles.clipsContent !== undefined && node.clipsContent === undefined) node.clipsContent = styles.clipsContent;
  if (styles.overflowDirection && !node.overflowDirection) node.overflowDirection = styles.overflowDirection;
}
