import type { AnalysisNode } from "../contracts/figma-node.js";

/**
 * Style properties extracted from Tailwind/JSX code generated by Figma MCP get_design_context.
 * These are merged into AnalysisNode to enrich metadata-only nodes with style information.
 */
export interface ExtractedStyles {
  layoutMode?: "HORIZONTAL" | "VERTICAL";
  layoutPositioning?: "AUTO" | "ABSOLUTE";
  layoutSizingHorizontal?: "FIXED" | "HUG" | "FILL";
  layoutSizingVertical?: "FIXED" | "HUG" | "FILL";
  itemSpacing?: number;
  paddingLeft?: number;
  paddingRight?: number;
  paddingTop?: number;
  paddingBottom?: number;
  fills?: unknown[];
  effects?: unknown[];
}

/**
 * A code block from get_design_context, associated with a node ID.
 */
export interface DesignContextBlock {
  nodeId: string;
  code: string;
}

// Tailwind spacing scale: class suffix → px value
const SPACING_SCALE: Record<string, number> = {
  "0": 0, "px": 1, "0.5": 2, "1": 4, "1.5": 6, "2": 8, "2.5": 10,
  "3": 12, "3.5": 14, "4": 16, "5": 20, "6": 24, "7": 28, "8": 32,
  "9": 36, "10": 40, "11": 44, "12": 48, "14": 56, "16": 64,
  "20": 80, "24": 96, "28": 112, "32": 128, "36": 144, "40": 160,
  "44": 176, "48": 192, "52": 208, "56": 224, "60": 240, "64": 256,
  "72": 288, "80": 320, "96": 384,
};

function resolveSpacing(value: string): number | undefined {
  // Arbitrary value: gap-[12px]
  const arbMatch = value.match(/^\[(\d+(?:\.\d+)?)px\]$/);
  if (arbMatch?.[1]) return parseFloat(arbMatch[1]);
  return SPACING_SCALE[value];
}

/**
 * Extract style properties from a className string (Tailwind classes).
 */
export function extractStylesFromClasses(classes: string): ExtractedStyles {
  const styles: ExtractedStyles = {};
  const tokens = classes.split(/\s+/);

  for (const token of tokens) {
    // Layout direction
    if (token === "flex" || token === "flex-row") {
      styles.layoutMode = "HORIZONTAL";
    } else if (token === "flex-col") {
      styles.layoutMode = "VERTICAL";
    }

    // Positioning
    else if (token === "absolute") {
      styles.layoutPositioning = "ABSOLUTE";
    } else if (token === "relative" || token === "static") {
      styles.layoutPositioning = "AUTO";
    }

    // Sizing
    else if (token === "w-full") {
      styles.layoutSizingHorizontal = "FILL";
    } else if (token === "h-full") {
      styles.layoutSizingVertical = "FILL";
    } else if (token === "w-fit") {
      styles.layoutSizingHorizontal = "HUG";
    } else if (token === "h-fit") {
      styles.layoutSizingVertical = "HUG";
    } else if (token.match(/^w-\[.+\]$/) || token.match(/^w-\d/)) {
      styles.layoutSizingHorizontal = "FIXED";
    } else if (token.match(/^h-\[.+\]$/) || token.match(/^h-\d/)) {
      styles.layoutSizingVertical = "FIXED";
    }

    // Gap → itemSpacing
    else if (token.startsWith("gap-")) {
      const val = token.slice(4);
      const px = resolveSpacing(val);
      if (px !== undefined) styles.itemSpacing = px;
    }

    // Padding
    else if (token.startsWith("p-") && !token.startsWith("pl-") && !token.startsWith("pr-") && !token.startsWith("pt-") && !token.startsWith("pb-") && !token.startsWith("px-") && !token.startsWith("py-")) {
      const val = token.slice(2);
      const px = resolveSpacing(val);
      if (px !== undefined) {
        styles.paddingLeft = px;
        styles.paddingRight = px;
        styles.paddingTop = px;
        styles.paddingBottom = px;
      }
    } else if (token.startsWith("px-")) {
      const px = resolveSpacing(token.slice(3));
      if (px !== undefined) {
        styles.paddingLeft = px;
        styles.paddingRight = px;
      }
    } else if (token.startsWith("py-")) {
      const px = resolveSpacing(token.slice(3));
      if (px !== undefined) {
        styles.paddingTop = px;
        styles.paddingBottom = px;
      }
    } else if (token.startsWith("pl-")) {
      const px = resolveSpacing(token.slice(3));
      if (px !== undefined) styles.paddingLeft = px;
    } else if (token.startsWith("pr-")) {
      const px = resolveSpacing(token.slice(3));
      if (px !== undefined) styles.paddingRight = px;
    } else if (token.startsWith("pt-")) {
      const px = resolveSpacing(token.slice(3));
      if (px !== undefined) styles.paddingTop = px;
    } else if (token.startsWith("pb-")) {
      const px = resolveSpacing(token.slice(3));
      if (px !== undefined) styles.paddingBottom = px;
    }

    // Background color → fills
    else if (token.startsWith("bg-[")) {
      const colorMatch = token.match(/^bg-\[(.+)\]$/);
      if (colorMatch?.[1]) {
        const color = colorMatch[1];
        if (!styles.fills) styles.fills = [];
        if (color.startsWith("var(")) {
          // Design token reference: bg-[var(--md-sys-color-surface)]
          styles.fills.push({ type: "SOLID", color: {}, boundVariable: color });
        } else {
          // Raw color: bg-[#FF0000]
          styles.fills.push({ type: "SOLID", color: parseHexColor(color) });
        }
      }
    }

    // Shadow → effects
    else if (token === "shadow" || token.startsWith("shadow-")) {
      if (!styles.effects) styles.effects = [];
      styles.effects.push({ type: "DROP_SHADOW" });
    }
  }

  return styles;
}

function parseHexColor(hex: string): Record<string, number> {
  const clean = hex.replace("#", "");
  if (clean.length === 6 || clean.length === 8) {
    return {
      r: parseInt(clean.slice(0, 2), 16) / 255,
      g: parseInt(clean.slice(2, 4), 16) / 255,
      b: parseInt(clean.slice(4, 6), 16) / 255,
      a: clean.length === 8 ? parseInt(clean.slice(6, 8), 16) / 255 : 1,
    };
  }
  return { r: 0, g: 0, b: 0, a: 1 };
}

/**
 * Extract className values from the root-level JSX element in a code block.
 * Returns classes from the first/outermost div/element's className.
 */
function extractRootClasses(code: string): string {
  // Match the first className="..." in the JSX
  const match = code.match(/className="([^"]+)"/);
  return match?.[1] ?? "";
}

/**
 * Extract all className values from entire code block.
 * Returns aggregated style info for all elements.
 */
function extractAllClasses(code: string): string[] {
  const classes: string[] = [];
  const regex = /className="([^"]+)"/g;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(code)) !== null) {
    if (match[1]) classes.push(match[1]);
  }
  return classes;
}

/**
 * Parse a get_design_context code response to extract style hints
 * for enriching AnalysisNode properties.
 *
 * The code is React+Tailwind generated by Figma MCP. We extract:
 * - Root element styles (layoutMode, padding, gap, sizing)
 * - Color fills (bg-[#hex] or bg-[var(...)])
 * - Shadow effects
 * - Layout positioning (absolute/relative)
 */
export function parseDesignContextCode(code: string): ExtractedStyles {
  const rootClasses = extractRootClasses(code);
  const rootStyles = extractStylesFromClasses(rootClasses);

  // Also scan all elements for fills and effects to capture deeper style info
  const allClasses = extractAllClasses(code);
  const aggregatedFills: unknown[] = [...(rootStyles.fills ?? [])];
  const aggregatedEffects: unknown[] = [...(rootStyles.effects ?? [])];

  for (const cls of allClasses) {
    const styles = extractStylesFromClasses(cls);
    if (styles.fills) {
      for (const fill of styles.fills) aggregatedFills.push(fill);
    }
    if (styles.effects) {
      for (const effect of styles.effects) aggregatedEffects.push(effect);
    }
  }

  return {
    ...rootStyles,
    ...(aggregatedFills.length > 0 ? { fills: aggregatedFills } : {}),
    ...(aggregatedEffects.length > 0 ? { effects: aggregatedEffects } : {}),
  };
}

/**
 * Parse the comment header from get_design_context code to extract node metadata.
 * Format: "/* NodeName — 905x680 COMPONENT, vertical auto-layout *\/"
 */
export function parseCodeHeader(code: string): {
  name?: string;
  width?: number;
  height?: number;
  type?: string;
  hasAutoLayout?: boolean;
  layoutDirection?: "HORIZONTAL" | "VERTICAL";
} {
  const headerMatch = code.match(/\/\*\s*(.+?)\s*\*\//);
  if (!headerMatch?.[1]) return {};

  const header = headerMatch[1];
  const result: ReturnType<typeof parseCodeHeader> = {};

  // Extract name (before " — ")
  const nameParts = header.split(" — ");
  if (nameParts[0]) result.name = nameParts[0].trim();

  // Extract dimensions
  const dimMatch = header.match(/(\d+)x(\d+)/);
  if (dimMatch?.[1] && dimMatch[2]) {
    result.width = parseInt(dimMatch[1]);
    result.height = parseInt(dimMatch[2]);
  }

  // Extract type
  const typeMatch = header.match(/\b(COMPONENT|FRAME|INSTANCE|GROUP|SECTION)\b/);
  if (typeMatch?.[1]) result.type = typeMatch[1];

  // Auto-layout detection
  if (header.includes("no auto-layout")) {
    result.hasAutoLayout = false;
  } else if (header.includes("auto-layout")) {
    result.hasAutoLayout = true;
    if (header.includes("vertical auto-layout")) result.layoutDirection = "VERTICAL";
    else if (header.includes("horizontal auto-layout")) result.layoutDirection = "HORIZONTAL";
  }

  return result;
}

/**
 * Merge extracted styles into an AnalysisNode (mutates the node).
 * Only sets properties that are not already present on the node.
 */
export function enrichNodeWithStyles(node: AnalysisNode, styles: ExtractedStyles): void {
  if (styles.layoutMode && !node.layoutMode) node.layoutMode = styles.layoutMode;
  if (styles.layoutPositioning && !node.layoutPositioning) node.layoutPositioning = styles.layoutPositioning;
  if (styles.layoutSizingHorizontal && !node.layoutSizingHorizontal) node.layoutSizingHorizontal = styles.layoutSizingHorizontal;
  if (styles.layoutSizingVertical && !node.layoutSizingVertical) node.layoutSizingVertical = styles.layoutSizingVertical;
  if (styles.itemSpacing !== undefined && node.itemSpacing === undefined) node.itemSpacing = styles.itemSpacing;
  if (styles.paddingLeft !== undefined && node.paddingLeft === undefined) node.paddingLeft = styles.paddingLeft;
  if (styles.paddingRight !== undefined && node.paddingRight === undefined) node.paddingRight = styles.paddingRight;
  if (styles.paddingTop !== undefined && node.paddingTop === undefined) node.paddingTop = styles.paddingTop;
  if (styles.paddingBottom !== undefined && node.paddingBottom === undefined) node.paddingBottom = styles.paddingBottom;
  if (styles.fills && !node.fills) node.fills = styles.fills;
  if (styles.effects && !node.effects) node.effects = styles.effects;
}
