// Report HTML module - HTML report generation

import type { AnalysisFile } from "../contracts/figma-node.js";
import type { Category } from "../contracts/category.js";
import { CATEGORIES, CATEGORY_LABELS } from "../contracts/category.js";
import { SEVERITY_LABELS } from "../contracts/severity.js";
import type { AnalysisResult, AnalysisIssue } from "../core/rule-engine.js";
import type { ScoreReport } from "../core/scoring.js";
import { buildFigmaDeepLink } from "../adapters/figma-url-parser.js";
import type { VisualComparisonRecord } from "../agents/contracts/visual-comparison.js";

/**
 * Node screenshot for analyze --visual (Figma preview only, no comparison)
 */
export interface NodeScreenshot {
  nodeId: string;
  nodePath: string;
  screenshotBase64: string;
  issueCount: number;
  topSeverity: string;
}

export interface HtmlReportOptions {
  visualComparisons?: VisualComparisonRecord[];
  nodeScreenshots?: NodeScreenshot[];
}

/**
 * Generate a static HTML report with optional visual sections
 */
export function generateHtmlReport(
  file: AnalysisFile,
  result: AnalysisResult,
  scores: ScoreReport,
  options?: HtmlReportOptions
): string {
  const visualComparisons = options?.visualComparisons;
  const nodeScreenshots = options?.nodeScreenshots;
  const quickWins = getQuickWins(result.issues, 5);
  const issuesByCategory = groupIssuesByCategory(result.issues);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Design Readiness Report - ${escapeHtml(file.name)}</title>
  <style>
${getStyles()}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>Design Readiness Report</h1>
      <p class="file-name">${escapeHtml(file.name)}</p>
      <p class="meta">Generated: ${new Date().toLocaleString()} | Nodes: ${result.nodeCount} | Max Depth: ${result.maxDepth}</p>
    </header>

    <section class="overall-score">
      <div class="grade grade-${scores.overall.grade}">${scores.overall.grade}</div>
      <div class="score-details">
        <div class="percentage">${scores.overall.percentage}%</div>
        <div class="score-label">Overall Score</div>
      </div>
    </section>

    <section class="summary">
      <h2>Issue Summary</h2>
      <div class="summary-grid">
        <div class="summary-item severity-blocking">
          <span class="count">${scores.summary.blocking}</span>
          <span class="label">Blocking</span>
        </div>
        <div class="summary-item severity-risk">
          <span class="count">${scores.summary.risk}</span>
          <span class="label">Risk</span>
        </div>
        <div class="summary-item severity-missing-info">
          <span class="count">${scores.summary.missingInfo}</span>
          <span class="label">Missing Info</span>
        </div>
        <div class="summary-item severity-suggestion">
          <span class="count">${scores.summary.suggestion}</span>
          <span class="label">Suggestion</span>
        </div>
      </div>
    </section>

    <section class="categories">
      <h2>Category Scores</h2>
      <div class="category-grid">
${CATEGORIES.map(cat => renderCategoryCard(cat, scores)).join("\n")}
      </div>
    </section>

${quickWins.length > 0 ? renderQuickWins(quickWins, file.fileKey) : ""}

    <section class="issues">
      <h2>All Issues (${result.issues.length})</h2>
${CATEGORIES.map(cat => renderCategoryIssues(cat, issuesByCategory.get(cat) ?? [], file.fileKey)).join("\n")}
    </section>

${nodeScreenshots && nodeScreenshots.length > 0 ? renderNodeScreenshotSection(nodeScreenshots, file.fileKey) : ""}
${visualComparisons && visualComparisons.length > 0 ? renderVisualComparisonSection(visualComparisons) : ""}

    <footer>
      <p>Generated by <strong>Design Readiness Checker</strong></p>
    </footer>
  </div>
</body>
</html>`;
}

function getStyles(): string {
  return `
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #1a1a1a;
      background: #f5f5f5;
    }

    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 2rem;
    }

    header {
      text-align: center;
      margin-bottom: 2rem;
    }

    header h1 {
      font-size: 2rem;
      margin-bottom: 0.5rem;
    }

    .file-name {
      font-size: 1.25rem;
      color: #666;
    }

    .meta {
      font-size: 0.875rem;
      color: #999;
      margin-top: 0.5rem;
    }

    section {
      background: white;
      border-radius: 12px;
      padding: 1.5rem;
      margin-bottom: 1.5rem;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }

    h2 {
      font-size: 1.25rem;
      margin-bottom: 1rem;
      color: #333;
    }

    .overall-score {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 2rem;
    }

    .grade {
      width: 120px;
      height: 120px;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 3rem;
      font-weight: bold;
      color: white;
    }

    .grade-A { background: linear-gradient(135deg, #10b981, #059669); }
    .grade-B { background: linear-gradient(135deg, #3b82f6, #2563eb); }
    .grade-C { background: linear-gradient(135deg, #f59e0b, #d97706); }
    .grade-D { background: linear-gradient(135deg, #f97316, #ea580c); }
    .grade-F { background: linear-gradient(135deg, #ef4444, #dc2626); }

    .score-details {
      text-align: left;
    }

    .percentage {
      font-size: 3rem;
      font-weight: bold;
      color: #333;
    }

    .score-label {
      color: #666;
      font-size: 1rem;
    }

    .summary-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 1rem;
    }

    .summary-item {
      padding: 1rem;
      border-radius: 8px;
      text-align: center;
    }

    .summary-item .count {
      display: block;
      font-size: 2rem;
      font-weight: bold;
    }

    .summary-item .label {
      font-size: 0.875rem;
      color: #666;
    }

    .severity-blocking { background: #fef2f2; }
    .severity-blocking .count { color: #dc2626; }

    .severity-risk { background: #fff7ed; }
    .severity-risk .count { color: #ea580c; }

    .severity-missing-info { background: #fefce8; }
    .severity-missing-info .count { color: #ca8a04; }

    .severity-suggestion { background: #f0fdf4; }
    .severity-suggestion .count { color: #16a34a; }

    .category-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 1rem;
    }

    .category-card {
      padding: 1rem;
      border-radius: 8px;
      background: #f9fafb;
      border: 1px solid #e5e7eb;
    }

    .category-card h3 {
      font-size: 0.875rem;
      color: #666;
      margin-bottom: 0.5rem;
    }

    .category-card .score {
      font-size: 1.5rem;
      font-weight: bold;
    }

    .category-card .issues {
      font-size: 0.75rem;
      color: #999;
    }

    .quick-wins {
      background: #fffbeb;
      border: 1px solid #fcd34d;
    }

    .quick-wins h2 {
      color: #b45309;
    }

    .issue-list {
      list-style: none;
    }

    .issue-item {
      padding: 1rem;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      margin-bottom: 0.75rem;
      background: #fafafa;
    }

    .issue-header {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      margin-bottom: 0.5rem;
    }

    .severity-badge {
      padding: 0.25rem 0.5rem;
      border-radius: 4px;
      font-size: 0.75rem;
      font-weight: 600;
      text-transform: uppercase;
    }

    .badge-blocking { background: #fee2e2; color: #dc2626; }
    .badge-risk { background: #ffedd5; color: #ea580c; }
    .badge-missing-info { background: #fef9c3; color: #ca8a04; }
    .badge-suggestion { background: #dcfce7; color: #16a34a; }

    .issue-message {
      font-weight: 500;
      color: #333;
    }

    .issue-path {
      font-size: 0.75rem;
      color: #666;
      font-family: monospace;
      margin: 0.5rem 0;
    }

    .issue-details {
      font-size: 0.875rem;
      color: #666;
      margin-top: 0.5rem;
    }

    .issue-details p {
      margin: 0.25rem 0;
    }

    .issue-details strong {
      color: #333;
    }

    .figma-link {
      display: inline-block;
      margin-top: 0.5rem;
      padding: 0.25rem 0.5rem;
      background: #f3f4f6;
      border-radius: 4px;
      font-size: 0.75rem;
      color: #2563eb;
      text-decoration: none;
    }

    .figma-link:hover {
      background: #e5e7eb;
    }

    .category-section {
      margin-bottom: 1.5rem;
    }

    .category-section h3 {
      font-size: 1rem;
      color: #666;
      margin-bottom: 0.75rem;
      padding-bottom: 0.5rem;
      border-bottom: 1px solid #e5e7eb;
    }

    .no-issues {
      color: #16a34a;
      font-style: italic;
    }

    footer {
      text-align: center;
      padding: 2rem;
      color: #999;
      font-size: 0.875rem;
    }

    .node-screenshots-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
      gap: 1rem;
    }

    .ns-card {
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 0.75rem;
      background: #fafafa;
    }

    .ns-card img {
      width: 100%;
      border: 1px solid #e5e7eb;
      border-radius: 4px;
      margin-bottom: 0.5rem;
    }

    .ns-card h4 {
      font-size: 0.8rem;
      color: #333;
      margin-bottom: 0.25rem;
      word-break: break-all;
    }

    .ns-meta {
      font-size: 0.75rem;
      color: #666;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .visual-comparison-grid {
      display: grid;
      gap: 1.5rem;
    }

    .vc-card {
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 1rem;
      background: #fafafa;
    }

    .vc-card h3 {
      font-size: 0.95rem;
      margin-bottom: 0.75rem;
      color: #333;
    }

    .vc-images {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 1rem;
      margin-bottom: 1rem;
    }

    .vc-image-box {
      text-align: center;
    }

    .vc-image-box img {
      max-width: 100%;
      border: 1px solid #e5e7eb;
      border-radius: 4px;
    }

    .vc-image-box .vc-label {
      display: block;
      font-size: 0.75rem;
      color: #666;
      margin-bottom: 0.5rem;
      font-weight: 600;
    }

    .vc-similarity {
      font-size: 1.25rem;
      font-weight: bold;
      margin: 0.5rem 0;
    }

    .vc-similarity.good { color: #16a34a; }
    .vc-similarity.warn { color: #ca8a04; }
    .vc-similarity.poor { color: #dc2626; }

    .vc-details {
      font-size: 0.875rem;
      color: #666;
    }

    .vc-details p {
      margin: 0.25rem 0;
    }

    .vc-deep {
      margin-top: 0.75rem;
      padding: 0.75rem;
      background: #f0f9ff;
      border-radius: 6px;
      font-size: 0.875rem;
    }

    .vc-deep strong {
      color: #1e40af;
    }

    @media (max-width: 768px) {
      .container {
        padding: 1rem;
      }

      .summary-grid {
        grid-template-columns: repeat(2, 1fr);
      }

      .overall-score {
        flex-direction: column;
        gap: 1rem;
      }

      .score-details {
        text-align: center;
      }

      .vc-images {
        grid-template-columns: 1fr;
      }
    }
  `;
}

function renderCategoryCard(category: Category, scores: ScoreReport): string {
  const cat = scores.byCategory[category];
  const scoreColor = cat.percentage >= 80 ? "#16a34a" : cat.percentage >= 60 ? "#ca8a04" : "#dc2626";

  return `        <div class="category-card">
          <h3>${CATEGORY_LABELS[category]}</h3>
          <div class="score" style="color: ${scoreColor}">${cat.percentage}%</div>
          <div class="issues">${cat.issueCount} issues</div>
        </div>`;
}

function renderQuickWins(issues: AnalysisIssue[], fileKey: string): string {
  return `
    <section class="quick-wins">
      <h2>Quick Wins - Top Blocking Issues</h2>
      <p style="margin-bottom: 1rem; color: #92400e;">Fix these high-impact issues first for the biggest improvement.</p>
      <ul class="issue-list">
${issues.map(issue => renderIssueItem(issue, fileKey)).join("\n")}
      </ul>
    </section>`;
}

function renderCategoryIssues(
  category: Category,
  issues: AnalysisIssue[],
  fileKey: string
): string {
  return `      <div class="category-section">
        <h3>${CATEGORY_LABELS[category]} (${issues.length})</h3>
        ${issues.length === 0
          ? '<p class="no-issues">No issues found</p>'
          : `<ul class="issue-list">\n${issues.map(issue => renderIssueItem(issue, fileKey)).join("\n")}\n        </ul>`
        }
      </div>`;
}

function renderIssueItem(issue: AnalysisIssue, fileKey: string): string {
  const severity = issue.config.severity;
  const def = issue.rule.definition;
  const figmaLink = buildFigmaDeepLink(fileKey, issue.violation.nodeId);

  return `        <li class="issue-item">
          <div class="issue-header">
            <span class="severity-badge badge-${severity}">${SEVERITY_LABELS[severity]}</span>
            <span class="issue-message">${escapeHtml(issue.violation.message)}</span>
          </div>
          <div class="issue-path">${escapeHtml(issue.violation.nodePath)}</div>
          <div class="issue-details">
            <p><strong>Why:</strong> ${escapeHtml(def.why)}</p>
            <p><strong>Impact:</strong> ${escapeHtml(def.impact)}</p>
            <p><strong>Fix:</strong> ${escapeHtml(def.fix)}</p>
          </div>
          <a href="${figmaLink}" target="_blank" rel="noopener" class="figma-link">Open in Figma</a>
        </li>`;
}

function getQuickWins(issues: AnalysisIssue[], limit: number): AnalysisIssue[] {
  // Get blocking issues sorted by score impact (most negative first)
  return issues
    .filter(issue => issue.config.severity === "blocking")
    .sort((a, b) => a.calculatedScore - b.calculatedScore)
    .slice(0, limit);
}

function groupIssuesByCategory(issues: AnalysisIssue[]): Map<Category, AnalysisIssue[]> {
  const grouped = new Map<Category, AnalysisIssue[]>();

  for (const category of CATEGORIES) {
    grouped.set(category, []);
  }

  for (const issue of issues) {
    const category = issue.rule.definition.category;
    grouped.get(category)!.push(issue);
  }

  return grouped;
}

function renderNodeScreenshotSection(screenshots: NodeScreenshot[], fileKey: string): string {
  const cards = screenshots.map((ns) => {
    const badgeClass = ns.topSeverity === "blocking" ? "badge-blocking" : "badge-risk";
    const figmaLink = buildFigmaDeepLink(fileKey, ns.nodeId);

    return `<div class="ns-card">
        <img src="data:image/png;base64,${ns.screenshotBase64}" alt="${escapeHtml(ns.nodePath)}">
        <h4>${escapeHtml(ns.nodePath)}</h4>
        <div class="ns-meta">
          <span class="severity-badge ${badgeClass}">${escapeHtml(ns.topSeverity)} (${ns.issueCount})</span>
          <a href="${figmaLink}" target="_blank" rel="noopener" class="figma-link">Open in Figma</a>
        </div>
      </div>`;
  });

  return `
    <section>
      <h2>Node Previews (${screenshots.length})</h2>
      <p style="margin-bottom:1rem;color:#666;font-size:0.875rem">Figma screenshots of the most impactful nodes with blocking or risk issues.</p>
      <div class="node-screenshots-grid">
${cards.join("\n")}
      </div>
    </section>`;
}

function renderVisualComparisonSection(comparisons: VisualComparisonRecord[]): string {
  const cards = comparisons.map((vc) => {
    const similarity = 100 - vc.pixelComparison.pixelDiffPercentage;
    const cssClass = similarity >= 70 ? "good" : similarity >= 40 ? "warn" : "poor";
    const sizeNote = vc.pixelComparison.sizeMatch ? "" : " (size mismatch)";

    const deepSection = vc.deepComparison
      ? `<div class="vc-deep">
          <p><strong>AI Analysis:</strong> ${vc.deepComparison.similarityScore}% similarity</p>
          ${vc.deepComparison.diffAreas.length > 0 ? `<p><strong>Diff Areas:</strong> ${vc.deepComparison.diffAreas.map(a => escapeHtml(a)).join("; ")}</p>` : ""}
          ${vc.deepComparison.causeRuleIds.length > 0 ? `<p><strong>Cause Rules:</strong> ${vc.deepComparison.causeRuleIds.map(r => `<code>${escapeHtml(r)}</code>`).join(", ")}</p>` : ""}
        </div>`
      : "";

    const diffImage = vc.pixelComparison.diffImageBase64
      ? `<div class="vc-image-box">
          <span class="vc-label">Diff</span>
          <img src="data:image/png;base64,${vc.pixelComparison.diffImageBase64}" alt="Diff">
        </div>`
      : "";

    return `<div class="vc-card">
        <h3>${escapeHtml(vc.nodePath)} <span style="color:#999;font-weight:normal">(${escapeHtml(vc.nodeId)})</span></h3>
        <div class="vc-images">
          <div class="vc-image-box">
            <span class="vc-label">Figma Original</span>
            <img src="data:image/png;base64,${vc.figmaScreenshotBase64}" alt="Figma">
          </div>
          <div class="vc-image-box">
            <span class="vc-label">AI Implementation</span>
            <img src="data:image/png;base64,${vc.renderedScreenshotBase64}" alt="Rendered">
          </div>
        </div>
        <div class="vc-similarity ${cssClass}">Similarity: ${similarity.toFixed(1)}%${sizeNote}</div>
        <div class="vc-details">
          <p>Diff pixels: ${vc.pixelComparison.diffPixels} / ${vc.pixelComparison.totalPixels} (${vc.pixelComparison.width}x${vc.pixelComparison.height})</p>
        </div>
        ${diffImage}
        ${deepSection}
      </div>`;
  });

  return `
    <section>
      <h2>Visual Comparison (${comparisons.length})</h2>
      <div class="visual-comparison-grid">
${cards.join("\n")}
      </div>
    </section>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
