/**
 * Pure template functions for report HTML rendering.
 * No Node.js dependencies — usable in browser via CanICode.* globals.
 *
 * Single source of truth for all report UI:
 * - CLI: generateHtmlReport() wraps with <html> shell
 * - Web app: CanICode.renderReportBody() → innerHTML
 * - Figma plugin: CanICode.renderReportBody() → innerHTML
 *
 * Styled via self-contained CSS (app/shared/styles.css) — no Tailwind dependency.
 */

import type { Category } from "../contracts/category.js";
import type { Severity } from "../contracts/severity.js";
import type { AnalysisIssue } from "../engine/rule-engine.js";
import type { ScoreReport } from "../engine/scoring.js";
import { buildFigmaDeepLink } from "../adapters/figma-url-parser.js";
import {
  CATEGORIES,
  CATEGORY_LABELS,
  SEVERITY_LABELS,
  CATEGORY_DESCRIPTIONS,
  SEVERITY_ORDER,
} from "../ui-constants.js";
import {
  escapeHtml,
  severityDot,
  severityBadge,
  scoreBadgeStyle,
  renderGaugeSvg,
} from "../ui-helpers.js";

// ---- Data interface ----

export interface ReportData {
  fileName: string;
  fileKey: string;
  scores: ScoreReport;
  issues: AnalysisIssue[];
  nodeCount: number;
  maxDepth: number;
  figmaToken?: string;
}

// ---- Main render ----

/**
 * Render the report body content (everything inside <main>).
 * Does NOT include <html>, <head>, <body> — caller wraps as needed.
 */
export function renderReportBody(data: ReportData): string {
  const { scores, issues, fileKey, figmaToken } = data;
  const quickWins = getQuickWins(issues, 5);
  const issuesByCategory = groupIssuesByCategory(issues);

  return `
    <!-- Overall Score -->
    <section class="rpt-overall">
      ${renderGaugeSvg(scores.overall.percentage, 200, 10, scores.overall.grade)}
      <div class="rpt-score">
        <span class="rpt-score-value">${scores.overall.percentage}</span>
        <span class="rpt-score-max">/ 100</span>
      </div>
      <p class="rpt-score-label">Overall Score</p>
    </section>

    <!-- Category Gauges -->
    <section class="card rpt-gauges">
      <div class="rpt-gauges-grid">
${CATEGORIES.map(cat => {
    const cs = scores.byCategory[cat];
    const desc = CATEGORY_DESCRIPTIONS[cat];
    return `        <a href="#cat-${cat}" class="rpt-gauge-item" title="${esc(desc)}">
          ${renderGaugeSvg(cs.percentage, 100, 7)}
          <span class="rpt-gauge-label">${CATEGORY_LABELS[cat]}</span>
          <span class="rpt-gauge-count">${cs.issueCount} issues</span>
        </a>`;
  }).join("\n")}
      </div>
    </section>

    <!-- Issue Summary -->
    <section class="card rpt-summary">
      <div class="rpt-summary-inner">
        ${renderSummaryDot("sev-blocking", scores.summary.blocking, "Blocking")}
        ${renderSummaryDot("sev-risk", scores.summary.risk, "Risk")}
        ${renderSummaryDot("sev-missing", scores.summary.missingInfo, "Missing Info")}
        ${renderSummaryDot("sev-suggestion", scores.summary.suggestion, "Suggestion")}
        <div class="rpt-summary-total">
          <span class="rpt-summary-count">${scores.summary.totalIssues}</span>
          <span class="rpt-summary-label">Total</span>
        </div>
      </div>
    </section>

${quickWins.length > 0 ? renderOpportunities(quickWins, fileKey) : ""}

    <!-- Categories -->
    <div class="rpt-cats">
${CATEGORIES.map(cat => renderCategory(cat, scores, issuesByCategory.get(cat) ?? [], fileKey, figmaToken)).join("\n")}
    </div>

    <!-- Footer -->
    <footer class="rpt-footer">
      <p class="rpt-footer-main">Generated by <strong>CanICode</strong></p>
      <p class="rpt-footer-meta">${new Date().toLocaleString()} · ${data.nodeCount} nodes · Max depth ${data.maxDepth}</p>
    </footer>`;
}

// ---- Components ----

const SEVERITY_TOOLTIPS: Record<string, string> = {
  Blocking: "Cannot implement correctly without fixing. Direct impact on screen reproduction.",
  Risk: "Implementable now but will break or increase cost later.",
  "Missing Info": "Information is absent, forcing AI to guess.",
  Suggestion: "Not immediately problematic, but improves systemization.",
};

export function renderSummaryDot(sevClass: string, count: number, label: string): string {
  const tooltip = SEVERITY_TOOLTIPS[label] ?? "";
  return `<div class="rpt-summary-item" title="${esc(tooltip)}">
          <span class="rpt-dot ${sevClass}"></span>
          <span class="rpt-summary-count">${count}</span>
          <span class="rpt-summary-label">${label}</span>
        </div>`;
}

export function renderOpportunities(issues: AnalysisIssue[], fileKey: string): string {
  const maxAbs = issues.reduce((m, i) => Math.max(m, Math.abs(i.calculatedScore)), 1);
  return `
    <!-- Opportunities -->
    <section class="card rpt-opps">
      <div class="rpt-opps-header">
        <h2 class="rpt-opps-title">
          <span class="rpt-dot sev-blocking"></span>
          Opportunities
        </h2>
        <p class="rpt-opps-desc">Top blocking issues — fix these first for the biggest improvement.</p>
      </div>
      <div class="rpt-opps-list">
${issues.map(issue => {
    const def = issue.rule.definition;
    const link = buildFigmaDeepLink(fileKey, issue.violation.nodeId);
    const barW = Math.round((Math.abs(issue.calculatedScore) / maxAbs) * 100);
    return `        <div class="rpt-opps-item">
          <div class="rpt-opps-info">
            <div class="rpt-opps-name">${esc(def.name)}</div>
            <div class="rpt-opps-msg">${esc(issue.violation.message)}</div>
          </div>
          <div class="rpt-opps-bar-wrap">
            <div class="rpt-opps-bar">
              <div class="rpt-opps-bar-fill" style="width:${barW}%"></div>
            </div>
            <span class="rpt-opps-score">${issue.calculatedScore}</span>
          </div>
          <a href="${link}" target="_blank" rel="noopener" data-node-id="${esc(issue.violation.nodeId)}" class="rpt-opps-link no-print">Go to node →</a>
        </div>`;
  }).join("\n")}
      </div>
    </section>`;
}

export function renderCategory(
  cat: Category,
  scores: ScoreReport,
  issues: AnalysisIssue[],
  fileKey: string,
  figmaToken?: string
): string {
  const cs = scores.byCategory[cat];
  const hasProblems = issues.some(i => i.config.severity === "blocking" || i.config.severity === "risk");

  const bySeverity = new Map<Severity, AnalysisIssue[]>();
  for (const sev of SEVERITY_ORDER) bySeverity.set(sev, []);
  for (const issue of issues) bySeverity.get(issue.config.severity)?.push(issue);

  return `
      <details id="cat-${cat}" class="card rpt-cat"${hasProblems ? " open" : ""}>
        <summary class="rpt-cat-header">
          <span class="rpt-badge ${scoreBadgeStyle(cs.percentage)}">${cs.percentage}</span>
          <div class="rpt-cat-info">
            <div class="rpt-cat-name">${CATEGORY_LABELS[cat]}</div>
            <div class="rpt-cat-desc">${esc(CATEGORY_DESCRIPTIONS[cat])}</div>
          </div>
          <span class="rpt-cat-count">${cs.issueCount} issues</span>
          <svg class="rpt-cat-chevron no-print" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M19 9l-7 7-7-7"/></svg>
        </summary>
        <div class="rpt-cat-body">
${issues.length === 0
    ? '          <div class="rpt-cat-empty">No issues found</div>'
    : SEVERITY_ORDER
        .filter(sev => (bySeverity.get(sev)?.length ?? 0) > 0)
        .map(sev => renderSeverityGroup(sev, bySeverity.get(sev) ?? [], fileKey, figmaToken))
        .join("\n")
}
        </div>
      </details>`;
}

export function renderSeverityGroup(
  sev: Severity,
  issues: AnalysisIssue[],
  fileKey: string,
  figmaToken?: string
): string {
  return `          <div class="rpt-sev-group">
            <div class="rpt-sev-header">
              <span class="rpt-dot-sm ${severityDot(sev)}"></span>
              <span class="rpt-sev-label">${SEVERITY_LABELS[sev]}</span>
              <span class="rpt-sev-count">${issues.length}</span>
            </div>
            <div class="rpt-sev-issues">
${issues.map(issue => renderIssueRow(issue, fileKey, figmaToken)).join("\n")}
            </div>
          </div>`;
}

export function renderIssueRow(
  issue: AnalysisIssue,
  fileKey: string,
  figmaToken?: string
): string {
  const sev = issue.config.severity;
  const def = issue.rule.definition;
  const link = buildFigmaDeepLink(fileKey, issue.violation.nodeId);

  return `              <details class="rpt-issue">
                <summary class="rpt-issue-header">
                  <span class="rpt-dot-sm ${severityDot(sev)}"></span>
                  <span class="rpt-issue-name">${esc(def.name)}</span>
                  <span class="rpt-issue-msg">${esc(issue.violation.message)}</span>
                  <span class="rpt-issue-score ${severityBadge(sev)}">${issue.calculatedScore}</span>
                </summary>
                <div class="rpt-issue-body">
                  <div class="rpt-issue-path">${esc(issue.violation.nodePath)}</div>
                  <div class="rpt-issue-info">
                    <p><strong>Why:</strong> ${esc(def.why)}</p>
                    <p><strong>Impact:</strong> ${esc(def.impact)}</p>
                    <p><strong>Fix:</strong> ${esc(def.fix)}</p>
                  </div>
                  <div class="rpt-issue-actions no-print">
                    <a href="${link}" target="_blank" rel="noopener" data-node-id="${esc(issue.violation.nodeId)}" class="rpt-btn">Go to node <span>→</span></a>${figmaToken ? `
                    <button onclick="postComment(this)" data-file-key="${esc(fileKey)}" data-node-id="${esc(issue.violation.nodeId)}" data-message="${esc(issue.violation.message)}" class="rpt-btn">Comment on Figma</button>` : ""}
                  </div>
                </div>
              </details>`;
}

// ---- Utils ----

function getQuickWins(issues: AnalysisIssue[], limit: number): AnalysisIssue[] {
  return issues
    .filter(issue => issue.config.severity === "blocking")
    .sort((a, b) => a.calculatedScore - b.calculatedScore)
    .slice(0, limit);
}

function groupIssuesByCategory(issues: AnalysisIssue[]): Map<Category, AnalysisIssue[]> {
  const grouped = new Map<Category, AnalysisIssue[]>();
  for (const category of CATEGORIES) grouped.set(category, []);
  for (const issue of issues) grouped.get(issue.rule.definition.category)!.push(issue);
  return grouped;
}

const esc = escapeHtml;
