/**
 * Auto-generate rule documentation from rule-config.ts + rule registry.
 *
 * Usage: npx tsx scripts/sync-rule-docs.ts
 *
 * Updates:
 * 1. docs/CUSTOMIZATION.md — rule tables between RULE_TABLE markers
 * 2. Wiki Rule-Reference.md — full rule reference page (if wiki clone exists at /tmp/canicode-wiki/)
 */

// Import rules to populate registry
import "../src/core/rules/index.js";
import { ruleRegistry } from "../src/core/rules/rule-registry.js";
import { RULE_CONFIGS } from "../src/core/rules/rule-config.js";
import { CATEGORIES, CATEGORY_LABELS } from "../src/core/contracts/category.js";
import type { Category } from "../src/core/contracts/category.js";
import type { RuleId } from "../src/core/contracts/rule.js";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CUSTOMIZATION_PATH = resolve(__dirname, "../docs/CUSTOMIZATION.md");
const WIKI_PATH = "/tmp/canicode-wiki/Rule-Reference.md";
const START_MARKER = "<!-- RULE_TABLE_START";
const END_MARKER = "<!-- RULE_TABLE_END -->";

// ---- Shared data helpers ----

interface RuleEntry {
  id: RuleId;
  name: string;
  category: Category;
  score: number;
  severity: string;
  enabled: boolean;
  why: string;
  impact: string;
  fix: string;
  options?: Record<string, unknown>;
}

function getRulesByCategory(): Map<Category, RuleEntry[]> {
  const result = new Map<Category, RuleEntry[]>();
  for (const category of CATEGORIES) {
    const rules = ruleRegistry
      .getByCategory(category as Category)
      .map((r) => {
        const id = r.definition.id as RuleId;
        const config = RULE_CONFIGS[id];
        if (!config) {
          throw new Error(`Missing RULE_CONFIGS entry for rule "${id}"`);
        }
        return {
          id,
          name: r.definition.name,
          category: r.definition.category,
          score: config.score,
          severity: config.severity,
          enabled: config.enabled ?? true,
          why: r.definition.why,
          impact: r.definition.impact,
          fix: r.definition.fix,
          options: config.options as Record<string, unknown> | undefined,
        };
      });
    result.set(category as Category, rules);
  }
  return result;
}

// ---- 1. CUSTOMIZATION.md tables ----

function generateCustomizationTables(rulesByCategory: Map<Category, RuleEntry[]>): string {
  const lines: string[] = [];

  for (const category of CATEGORIES) {
    const rules = rulesByCategory.get(category as Category) ?? [];
    const label = CATEGORY_LABELS[category as Category];
    lines.push(`**${label} (${rules.length} rules)**`);
    lines.push("");
    lines.push("| Rule ID | Default Score | Default Severity |");
    lines.push("|---------|--------------|-----------------|");

    for (const rule of rules) {
      const disabledTag = rule.enabled ? "" : " *(disabled)*";
      lines.push(`| \`${rule.id}\`${disabledTag} | ${rule.score} | ${rule.severity} |`);
    }

    lines.push("");
  }

  if (lines.at(-1) === "") lines.pop();
  return lines.join("\n");
}

function syncCustomizationMd(rulesByCategory: Map<Category, RuleEntry[]>): void {
  const content = readFileSync(CUSTOMIZATION_PATH, "utf-8");
  const startIdx = content.indexOf(START_MARKER);
  const endIdx = content.indexOf(END_MARKER);

  if (startIdx === -1 || endIdx === -1) {
    console.error("RULE_TABLE markers not found in CUSTOMIZATION.md");
    process.exit(1);
  }

  const before = content.slice(0, startIdx);
  const after = content.slice(endIdx + END_MARKER.length);
  const tables = generateCustomizationTables(rulesByCategory);

  const updated =
    before +
    `${START_MARKER} — auto-generated by scripts/sync-rule-docs.ts, do not edit manually -->\n` +
    tables +
    "\n" +
    END_MARKER +
    after;

  if (content === updated) {
    console.log("docs/CUSTOMIZATION.md is already up to date.");
  } else {
    writeFileSync(CUSTOMIZATION_PATH, updated, "utf-8");
    console.log("docs/CUSTOMIZATION.md updated.");
  }
}

// ---- 2. Wiki Rule-Reference.md ----

function generateWikiRuleReference(rulesByCategory: Map<Category, RuleEntry[]>): string {
  const totalRules = [...rulesByCategory.values()].reduce((sum, rules) => sum + rules.length, 0);
  const lines: string[] = [];

  lines.push(`Complete reference for all ${totalRules} analysis rules — auto-generated from rule-config.ts + rule registry.`);
  lines.push("");
  lines.push("> **This page is auto-generated** by \`scripts/sync-rule-docs.ts\`. Do not edit manually — changes will be overwritten.");
  lines.push("");

  for (const category of CATEGORIES) {
    const rules = rulesByCategory.get(category as Category) ?? [];
    const label = CATEGORY_LABELS[category as Category];

    lines.push("---");
    lines.push("");
    lines.push(`# ${label}`);
    lines.push("");

    for (const rule of rules) {
      const enabledTag = rule.enabled ? "" : " (DISABLED)";
      lines.push(`## \`${rule.id}\` (score: ${rule.score}, ${rule.severity})${enabledTag}`);
      lines.push("");
      lines.push(`**Why:** ${rule.why}`);
      lines.push("");
      lines.push(`**Impact:** ${rule.impact}`);
      lines.push("");
      lines.push(`**Fix:** ${rule.fix}`);

      if (rule.options && Object.keys(rule.options).length > 0) {
        lines.push("");
        lines.push("**Options:**");
        for (const [key, value] of Object.entries(rule.options)) {
          lines.push(`- \`${key}\`: \`${JSON.stringify(value)}\``);
        }
      }

      lines.push("");
    }
  }

  return lines.join("\n");
}

function syncWikiRuleReference(rulesByCategory: Map<Category, RuleEntry[]>): void {
  if (!existsSync("/tmp/canicode-wiki")) {
    console.log("Wiki clone not found at /tmp/canicode-wiki — skipping wiki sync.");
    return;
  }

  const generated = generateWikiRuleReference(rulesByCategory);

  if (existsSync(WIKI_PATH)) {
    const current = readFileSync(WIKI_PATH, "utf-8");
    if (current === generated) {
      console.log("Wiki Rule-Reference.md is already up to date.");
      return;
    }
  }

  writeFileSync(WIKI_PATH, generated, "utf-8");
  console.log("Wiki Rule-Reference.md updated at /tmp/canicode-wiki/Rule-Reference.md");
  console.log("  → cd /tmp/canicode-wiki && git add Rule-Reference.md && git commit -m 'docs: sync Rule Reference' && git push");
}

// ---- Main ----

const rulesByCategory = getRulesByCategory();
syncCustomizationMd(rulesByCategory);
syncWikiRuleReference(rulesByCategory);
