/**
 * Auto-generate rule tables in docs/REFERENCE.md from rule-config.ts + rule registry.
 *
 * Usage: npx tsx scripts/sync-rule-docs.ts
 *
 * Replaces content between RULE_TABLE_START and RULE_TABLE_END markers in REFERENCE.md.
 */

// Import rules to populate registry
import "../src/core/rules/index.js";
import { ruleRegistry } from "../src/core/rules/rule-registry.js";
import { RULE_CONFIGS } from "../src/core/rules/rule-config.js";
import { CATEGORIES } from "../src/core/contracts/category.js";
import type { Category } from "../src/core/contracts/category.js";
import type { RuleId } from "../src/core/contracts/rule.js";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REFERENCE_PATH = resolve(__dirname, "../docs/REFERENCE.md");
const START_MARKER = "<!-- RULE_TABLE_START";
const END_MARKER = "<!-- RULE_TABLE_END -->";

function generateTables(): string {
  const lines: string[] = [];

  for (const category of CATEGORIES) {
    const rules = ruleRegistry
      .getByCategory(category as Category)
      .map((r) => {
        const id = r.definition.id as RuleId;
        const config = RULE_CONFIGS[id];
        if (!config) {
          throw new Error(`Missing RULE_CONFIGS entry for rule "${id}"`);
        }
        return { id, config };
      });

    const label = category.charAt(0).toUpperCase() + category.slice(1);
    lines.push(`**${label} (${rules.length} rules)**`);
    lines.push("");
    lines.push("| Rule ID | Default Score | Default Severity |");
    lines.push("|---------|--------------|-----------------|");

    for (const { id, config } of rules) {
      lines.push(`| \`${id}\` | ${config.score} | ${config.severity} |`);
    }

    lines.push("");
  }

  // Remove trailing empty line
  if (lines.at(-1) === "") lines.pop();

  return lines.join("\n");
}

const content = readFileSync(REFERENCE_PATH, "utf-8");
const startIdx = content.indexOf(START_MARKER);
const endIdx = content.indexOf(END_MARKER);

if (startIdx === -1 || endIdx === -1) {
  console.error("RULE_TABLE markers not found in REFERENCE.md");
  process.exit(1);
}

const before = content.slice(0, startIdx);
const after = content.slice(endIdx + END_MARKER.length);
const tables = generateTables();

const updated =
  before +
  `${START_MARKER} — auto-generated by scripts/sync-rule-docs.ts, do not edit manually -->\n` +
  tables +
  "\n" +
  END_MARKER +
  after;

if (content === updated) {
  console.log("docs/REFERENCE.md is already up to date.");
} else {
  writeFileSync(REFERENCE_PATH, updated, "utf-8");
  console.log("docs/REFERENCE.md updated.");
}
